### PR TITLE
[Fixes #23] Fix default action payload

### LINKED ISSUE #23: Default action creators payload
Hi, I'm trying out autodux default action creators, and while writing tests noticed that instead of getting action like this one:
```javascript
{
    type: 'user/setUser',
    payload: {
        userName: 'Foo',
        avatar: 'foo.png'
    }
 }
```
I'm getting copy of an action inside payload, like this: 
```javascript
{
    type: 'user/setUser',
    payload: {
        type: 'user/setUser',
        payload: {
            userName: 'Foo',
            avatar: 'foo.png'
        }
     }
 }
```

Sample test:
```javascript
const {
    actions: {
        setUser
    },
    reducer
} = autodux({
    slice: 'user',
    initial: {
        userName: 'Anonymous',
        avatar: 'anonymous.png'
    }
});
const userName = 'Foo';
const avatar = 'foo.png';

const actual = setUser({ userName, avatar });
const expected = {
    type: 'user/setUser',
    payload: {
        userName,
        avatar,
    }
};
```

What am I doing wrong and how can I fix it so that default action creators form correct action?

### PR DESCRIPTION
**Pull request by Ellaylone**
resolves #23

### CODE REVIEW

**Comment by warrenv** [comment]
@ericelliott This looks to have fixed the problem.

File: src/test.js [hunk 1]
```diff
@@ -238,6 +238,33 @@ describe('autodux().selectors', async should => {
...
+    const userName = 'Foo';
+
+    const actual = setUserName(userName);
+    const expected = {
+      type: 'user/setUserName',
+      payload: userName,
+    };
+
+    assert({
+      given: 'default action',
```
Comment (ericelliott) [inline src/test.js]: Let's try "given no action for supplied initial state".

File: src/test.js [hunk 2]
```diff
@@ -238,6 +238,33 @@ describe('autodux().selectors', async should => {
...
+      should: 'create correct actions',
```
Comment (ericelliott) [inline src/test.js]: Try "should: return an action creator which returns an action with the correct type and payload"
